/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PaketRouteImport } from './routes/paket'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KameraRouteImport } from './routes/kamera'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as FrameRouteImport } from './routes/frame'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPaketRouteImport } from './routes/admin.paket'
import { Route as AdminKalenderRouteImport } from './routes/admin.kalender'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketRoute = PaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KameraRoute = KameraRouteImport.update({
  id: '/kamera',
  path: '/kamera',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameRoute = FrameRouteImport.update({
  id: '/frame',
  path: '/frame',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaketRoute = AdminPaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKalenderRoute = AdminKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/frame': typeof FrameRoute
  '/galeri': typeof GaleriRoute
  '/kamera': typeof KameraRoute
  '/login': typeof LoginRoute
  '/paket': typeof PaketRoute
  '/studio': typeof StudioRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/kalender': typeof AdminKalenderRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/frame': typeof FrameRoute
  '/galeri': typeof GaleriRoute
  '/kamera': typeof KameraRoute
  '/login': typeof LoginRoute
  '/paket': typeof PaketRoute
  '/studio': typeof StudioRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/kalender': typeof AdminKalenderRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/frame': typeof FrameRoute
  '/galeri': typeof GaleriRoute
  '/kamera': typeof KameraRoute
  '/login': typeof LoginRoute
  '/paket': typeof PaketRoute
  '/studio': typeof StudioRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/kalender': typeof AdminKalenderRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/frame'
    | '/galeri'
    | '/kamera'
    | '/login'
    | '/paket'
    | '/studio'
    | '/admin/bookings'
    | '/admin/export'
    | '/admin/kalender'
    | '/admin/paket'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/frame'
    | '/galeri'
    | '/kamera'
    | '/login'
    | '/paket'
    | '/studio'
    | '/admin/bookings'
    | '/admin/export'
    | '/admin/kalender'
    | '/admin/paket'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/frame'
    | '/galeri'
    | '/kamera'
    | '/login'
    | '/paket'
    | '/studio'
    | '/admin/bookings'
    | '/admin/export'
    | '/admin/kalender'
    | '/admin/paket'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingRoute: typeof BookingRoute
  FrameRoute: typeof FrameRoute
  GaleriRoute: typeof GaleriRoute
  KameraRoute: typeof KameraRoute
  LoginRoute: typeof LoginRoute
  PaketRoute: typeof PaketRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket': {
      id: '/paket'
      path: '/paket'
      fullPath: '/paket'
      preLoaderRoute: typeof PaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamera': {
      id: '/kamera'
      path: '/kamera'
      fullPath: '/kamera'
      preLoaderRoute: typeof KameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frame': {
      id: '/frame'
      path: '/frame'
      fullPath: '/frame'
      preLoaderRoute: typeof FrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paket': {
      id: '/admin/paket'
      path: '/paket'
      fullPath: '/admin/paket'
      preLoaderRoute: typeof AdminPaketRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kalender': {
      id: '/admin/kalender'
      path: '/kalender'
      fullPath: '/admin/kalender'
      preLoaderRoute: typeof AdminKalenderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminKalenderRoute: typeof AdminKalenderRoute
  AdminPaketRoute: typeof AdminPaketRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminExportRoute: AdminExportRoute,
  AdminKalenderRoute: AdminKalenderRoute,
  AdminPaketRoute: AdminPaketRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRoute,
  FrameRoute: FrameRoute,
  GaleriRoute: GaleriRoute,
  KameraRoute: KameraRoute,
  LoginRoute: LoginRoute,
  PaketRoute: PaketRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
